name: Deploy static web to GitHub Pages

on:
  push:
    branches:
      - static-web

permissions:
  id-token: write
  pages: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload static site
        uses: actions/upload-pages-artifact@v3
        with:
          path: web

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
